# Generated by Django 5.2.6 on 2026-02-15 07:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='login',
            field=models.CharField(max_length=50, default=''),
        ),
    ]
