# Generated by Django 5.2.6 on 2026-02-15 07:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sync_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, blank=True, null=True, default=''),
        ),
    ]
