# Generated by Django 5.2.6 on 2025-11-01 14:47

from django.db import migrations, models

def forwards(apps, schema_editor):
    Customer = apps.get_model('shop', 'Customer')

    # Получаем модель User динамически
    from django.conf import settings
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    conn = schema_editor.connection

    # Выбираем id и login напрямую из базы (чтобы не зависеть от исторической модели)
    with conn.cursor() as cursor:
        cursor.execute("SELECT id, login FROM customer WHERE user_id IS NULL")
        rows = cursor.fetchall()

    linked = 0
    created = 0
    skipped = 0

    for cid, login in rows:
        login = (login or '').strip()
        if not login:
            skipped += 1
            continue

        try:
            # пытаемся найти существующего пользователя по username
            user = User.objects.get(username=login)
            # обновляем связь
            Customer.objects.filter(pk=cid).update(user_id=user.pk)
            linked += 1
        except User.DoesNotExist:
            # пробуем создать пользователя с unusable password через менеджер, если это возможно
            try:
                manager = getattr(User, 'objects', None)
                if manager and hasattr(manager, 'create_user'):
                    # create_user может требовать email и др. поля у кастомной модели — если требует, он может упасть
                    user = manager.create_user(username=login, password=None)
                else:
                    # fallback: минимальный экземпляр
                    user = User(username=login)
                    if hasattr(user, 'set_unusable_password'):
                        user.set_unusable_password()
                    user.save()
                Customer.objects.filter(pk=cid).update(user_id=user.pk)
                created += 1
            except Exception:
                # если не получилось создать user (например, кастомная User требует дополнительные обязательные поля)
                skipped += 1
                continue

    # лог в stdout во время migrate
    print(f"Customers linked: {linked}; Users created: {created}; Skipped: {skipped}")

def backwards(apps, schema_editor):
    # Не делаем ничего при откате (или можно очистить user у customer, но это опасно)
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20251101_1737'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
