# Generated by Django 5.2.6 on 2026-02-15 07:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sync_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=30, blank=True, null=True, default=''),
        ),
    ]
