# Generated by Django 5.2.6 on 2026-02-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sync_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=1024, blank=True, null=True, default=''),
        ),
    ]
