# Generated by Django 5.2.6 on 2025-11-01 14:52

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20251101_1747'),
    ]

    operations = [
         migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                related_name='customer',
                null=False,
            ),
        ),
    ]
